# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pantryimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='pantry_image_path'),
        ),
    ]
