# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0002_auto_20170928_0749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pantryimage',
            name='pantry',
        ),
        migrations.RemoveField(
            model_name='weighteditem',
            name='pantry',
        ),
        migrations.AddField(
            model_name='pantry',
            name='completeImage',
            field=models.ImageField(null=True, upload_to=models.FilePathField(default=b'/pantry', path=b'/pantry')),
        ),
        migrations.AddField(
            model_name='pantry',
            name='imageLocation',
            field=models.FilePathField(default=b'/pantry', path=b'/pantry'),
        ),
        migrations.DeleteModel(
            name='PantryImage',
        ),
        migrations.DeleteModel(
            name='WeightedItem',
        ),
    ]
