# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0003_auto_20171107_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pantry',
            name='imageLocation',
        ),
        migrations.AlterField(
            model_name='pantry',
            name='completeImage',
            field=models.ImageField(blank=True, null=True, upload_to=b'media'),
        ),
    ]
